version: 2

sources:
  - name: staging
    database: robust-episode-412509
    schema: trips_data_all_us

    tables:
      - name: green_tripdata
      - name: green_tripdata_cleaned
      - name: yellow_tripdata
      - name: fhv_2019